import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

// Import the functions you need from the SDKs you need
import { initializeApp } from "firebase/app";
// TODO: Add SDKs for Firebase products that you want to use
// https://firebase.google.com/docs/web/setup#available-libraries
import { getAuth, signOut } from "firebase/auth";

import { firebaseConfig } from "../lib/firebase";

// Initialize Firebase
export const auth = getAuth(initializeApp(firebaseConfig));

const Home: NextPage = () => {
  const logout = () => {
    signOut(auth);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Firebase Sample</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>Firebase Sample Page</div>
        <button onClick={logout}>Logout</button>
      </main>
    </div>
  );
};

export default Home;
