import type { NextPage } from "next";
import Head from "next/head";

import { useEffect, useState } from "react";

import styles from "../styles/Home.module.css";

// Import the functions you need from the SDKs you need
import { initializeApp } from "firebase/app";
// TODO: Add SDKs for Firebase products that you want to use
// https://firebase.google.com/docs/web/setup#available-libraries
import { getAuth, signOut, onAuthStateChanged } from "firebase/auth";

import { firebaseConfig } from "../lib/firebase";

// Initialize Firebase
export const auth = getAuth(initializeApp(firebaseConfig));

const Home: NextPage = () => {
  const logout = () => {
    signOut(auth);
  };

  const [name, setName] = useState("");

  useEffect(() => {
    const authStateChanged = onAuthStateChanged(auth, async (user) => {
      const email = user?.email ? user.email : "no name";
      setName(email);
    });
    return () => {
      authStateChanged();
    };
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Firebase Sample</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>Firebase Sample Page</div>
        <button onClick={logout}>Logout</button>
        <div>{name}</div>
      </main>
    </div>
  );
};

export default Home;
