import type { NextPage } from "next";
import Head from "next/head";

import styles from "../styles/Home.module.css";

import { EmailAuthProvider } from "firebase/auth";
import StyledFirebaseAuth from "react-firebaseui/StyledFirebaseAuth";

import firebaseui from "firebaseui";

import { auth } from "./index";
const Login: NextPage = () => {
  const uiConfig: firebaseui.auth.Config = {
    signInFlow: "redirect",
    signInOptions: [
      {
        provider: EmailAuthProvider.PROVIDER_ID,
        disableSignUp: { status: true },
      },
    ],
    signInSuccessUrl: "/",
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Firebase Sample Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>Firebase Sample Login Page</div>
        <StyledFirebaseAuth firebaseAuth={auth} uiConfig={uiConfig} />;
      </main>
    </div>
  );
};

export default Login;
